version: 2.1

jobs:
  build_doc_r:
    machine:
      image: ubuntu-2004:202111-01

    steps:
      - checkout
      - run:
          name: Build documentation
          working_directory: docs
          command: |
            ./build-rdoc.sh

      - run:
          name: Check diff
          command: |
            set +e
            git add .
            PATCH_FILE="<< pipeline.git.revision >>.patch"
            git --no-pager diff --cached --exit-code > $PATCH_FILE
            failed=$?

            if [[ "$failed" == "1" ]]; then
              cat $PATCH_FILE
              MLFLOW_REPO_ID=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/mlflow/mlflow | jq '.id')
              PATCH_FILE_URL="https://output.circle-artifacts.com/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/${CIRCLE_NODE_INDEX}/${PATCH_FILE}"
              echo "========== Run the following commands to apply the diff above =========="
              echo "PATCH_FILE_URL=\"$PATCH_FILE_URL\""
              echo 'REDIRECTED_URL=$(curl -Ls -o /dev/null -w %{url_effective} $PATCH_FILE_URL)'
              echo 'curl -s $REDIRECTED_URL | git apply --verbose'
              echo "========================================================================"
            fi

            exit $failed

      - store_artifacts:
          path: << pipeline.git.revision >>.patch

  build_doc:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - run:
          name: Install Java
          command: |
            sudo apt-get update --yes
            sudo apt-get install default-jdk --yes
            sudo apt-get install maven --yes
            java -version
      - run:
          name: Install Python dependencies
          command: |
            pip --version
            pip install --progress-bar off -r requirements/doc-requirements.txt .
      - run:
          name: Build documentation
          working_directory: docs
          environment:
            JAVA_HOME: /usr/lib/jvm/default-java
          command: |
            make rsthtml
            make javadocs
      - store_artifacts:
          path: docs/build/html

  mlflow-recipes:
    docker:
      - image: cimg/python:3.8

    steps:
      - checkout
      - run:
          name: Pull submodule
          command: |
            git submodule update --init --recursive
      - run:
          name: Install dependencies
          command: |
            pip install -e .
            pip install nbconvert ipykernel matplotlib flaml
      - run:
          name: Run CLI
          working_directory: examples/recipes/regression
          environment:
            MLFLOW_RECIPES_PROFILE: local
          command: |
            mlflow recipes run
      - run:
          name: Run notebook
          working_directory: examples/recipes/regression
          environment:
            MLFLOW_RECIPES_PROFILE: local
          command: |
            jupyter nbconvert --to html --execute notebooks/jupyter.ipynb
      - store_artifacts:
          path: ~/.mlflow/recipes
      - store_artifacts:
          path: examples/recipes/regression/notebooks/jupyter.html

workflows:
  build:
    jobs:
      - build_doc
      - build_doc_r
      - mlflow-recipes
